apiVersion: extensions.gardener.cloud/v1alpha1
kind: ContainerRuntime
metadata:
  name: <shoot-worker-pool-name>
  namespace: shoot--dev--<shoot-name>
spec:
  binaryPath: /var/bin/containerruntimes
  type: gvisor
  workerPool:
    name: worker
    selector:
      matchLabels:
        worker.garden.sapcloud.io/group: worker
        worker.gardener.cloud/pool: worker