apiVersion: extensions.gardener.cloud/<>
kind: Infrastructure
metadata:
  name: <>
  namespace: shoot--<>
spec:
  type: aws
  region: eu-west-1
  secretRef:
    name: cloudprovider
    namespace: shoot--<>
  sshPublicKey: <>
  # providerConfig for AWS
  providerConfig:
    apiVersion: aws.provider.extensions.gardener.cloud/<>
    kind: InfrastructureConfig
    networks:
      vpc:
        # either provide VPC ID to reuse existing
        # or provide CIDR to create new VPC
        cidr: 10.240.0.0/16
      zones:
        - internal: 10.240.112.0/22
          name: eu-west-1a
          public: 10.240.96.0/22
          workers: 10.240.0.0/19