apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd-main
  namespace: shoot--dev--stestq6mjlvsv
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  serviceName: etcd-main
  template:
    spec:
      containers:
        - command:
            - /var/etcd/bin/bootstrap.sh
          image: quay.io/coreos/etcd:v3.3.17
          name: etcd
        - command:
            - etcdbrctl
            - server
            - --schedule=4 20 * * *
            - --data-dir=/var/etcd/data/new.etcd
            - --storage-provider=
            - --store-prefix=etcd-main
            - --cert=/var/etcd/ssl/client/tls.crt
            - --key=/var/etcd/ssl/client/tls.key
            - --cacert=/var/etcd/ssl/ca/ca.crt
            - --insecure-transport=false
            - --insecure-skip-tls-verify=false
            - --endpoints=https://etcd-main-0:2379
            - --etcd-connection-timeout=300
            - --delta-snapshot-period-seconds=300
            - --delta-snapshot-memory-limit=104857600
            - --garbage-collection-period-seconds=43200
            - --snapstore-temp-directory=/var/etcd/data/temp
          image: eu.gcr.io/gardener-project/gardener/etcdbrctl:0.7.3
          name: backup-restore
