apiVersion: extensions.gardener.cloud/<>
kind: Infrastructure
metadata:
  name: <>
  namespace: shoot--<>
spec: <>
status:
  providerStatus:
    kind: InfrastructureStatus
    apiVersion: aws.provider.extensions.gardener.cloud/<>
    ec2:
      keyName: shoot--<shoot-name>-ssh-publickey
    iam:
      instanceProfiles:
        - name: shoot--<>-nodes
          purpose: nodes
      roles:
        - arn: arn:aws:iam::<>:role/<>
          purpose: node
    vpc:
      id: vpc-<>
      securityGroups:
        - id: sg-<>
          purpose: nodes
      subnets:
        - id: subnet-<>
          purpose: nodes
          zone: eu-west-1a
        - id: subnet-<>
          purpose: public
          zone: eu-west-1a
  state:
    data: <terraform state for ControlPlane migration>
    encoding: base64