apiVersion: machine.sapcloud.io/<>
kind: MachineDeployment
metadata:
  name: shoot--<shootName>-<workerName>
  namespace: shoot--<>
spec:
  minReadySeconds: 500
  replicas: 3
  selector:
    matchLabels:
      name: <abc>
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: <abc>
    spec:
      class:
        kind: AWSMachineClass
        name: shoot--<>

status:
  availableReplicas: 3
  readyReplicas: 3
  replicas: 3
  unavailableReplicas: 0
  updatedReplicas: 3
